# Generated by Django 4.2.4 on 2023-08-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=30)),
                ("documento", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "empleados",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "idusuarios",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=30)),
                ("documento", models.CharField(max_length=30)),
            ],
        ),
    ]
